import '../models/board_position.dart';
import '../models/sokoban_level.dart';
import 'level_copy.dart';

final List<SokobanLevel> advancedLevels = [
  SokobanLevel(
    number: 15,
    title: levelCopy[14].title,
    description: levelCopy[14].description,
    layout: [
      '#############',
      '# TB    B T #',
      '# ### # ### #',
      '# #       # #',
      '# # ### #B# #',
      '#     #   T #',
      '# ###B# ### #',
      '#     T     #',
      '#############',
    ],
    initialPlayerPosition: BoardPosition(row: 1, column: 7),
  ),
  SokobanLevel(
    number: 16,
    title: levelCopy[15].title,
    description: levelCopy[15].description,
    layout: [
      '#############',
      '# T B TB BT #',
      '# ### ### # #',
      '#     #     #',
      '# # ### ### #',
      '# B       T #',
      '#############',
    ],
    initialPlayerPosition: BoardPosition(row: 1, column: 8),
  ),
  SokobanLevel(
    number: 17,
    title: levelCopy[16].title,
    description: levelCopy[16].description,
    layout: [
      '#########',
      '#TB    T#',
      '# ## # B#',
      '#    B  #',
      '#  # ## #',
      '#   T   #',
      '#########',
    ],
    initialPlayerPosition: BoardPosition(row: 3, column: 6),
  ),
  SokobanLevel(
    number: 18,
    title: levelCopy[17].title,
    description: levelCopy[17].description,
    layout: [
      '############',
      '#      B T #',
      '# #### ### #',
      '#    #     #',
      '###B #  ####',
      '#T         #',
      '# ### ####B#',
      '#  B   T  T#',
      '############',
    ],
    initialPlayerPosition: BoardPosition(row: 7, column: 4),
  ),
  SokobanLevel(
    number: 19,
    title: levelCopy[18].title,
    description: levelCopy[18].description,
    layout: [
      '##############',
      '#     #      #',
      '# TB  #   T  #',
      '# ### # ###B #',
      '#     #      #',
      '# ###   #### #',
      '#     #      #',
      '# T B # B T  #',
      '##############',
    ],
    initialPlayerPosition: BoardPosition(row: 2, column: 4),
  ),
  SokobanLevel(
    number: 20,
    title: levelCopy[19].title,
    description: levelCopy[19].description,
    layout: [
      '#############',
      '#         T #',
      '# ### ### # #',
      '#   # B   # #',
      '###B# ### # #',
      '#T    #     #',
      '# #B### ### #',
      '#   T  B  T #',
      '#############',
    ],
    initialPlayerPosition: BoardPosition(row: 3, column: 5),
  ),
];
