import '../models/board_position.dart';
import '../models/sokoban_level.dart';
import 'level_copy.dart';

final List<SokobanLevel> intermediateLevels = [
  SokobanLevel(
    number: 8,
    title: levelCopy[7].title,
    description: levelCopy[7].description,
    layout: [
      '###########',
      '# T B  BT #',
      '# ### ### #',
      '#         #',
      '# B ###   #',
      '# T       #',
      '###########',
    ],
    initialPlayerPosition: BoardPosition(row: 1, column: 5),
  ),
  SokobanLevel(
    number: 9,
    title: levelCopy[8].title,
    description: levelCopy[8].description,
    layout: [
      '##########',
      '#      T #',
      '#  ####B #',
      '#     #  #',
      '### B #  #',
      '#T       #',
      '##########',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 5),
  ),
  SokobanLevel(
    number: 10,
    title: levelCopy[9].title,
    description: levelCopy[9].description,
    layout: [
      '###########',
      '# T     T #',
      '# B#   #B #',
      '#  # # #  #',
      '#    #    #',
      '#  #  B#  #',
      '#    T    #',
      '###########',
    ],
    initialPlayerPosition: BoardPosition(row: 3, column: 8),
  ),
  SokobanLevel(
    number: 11,
    title: levelCopy[10].title,
    description: levelCopy[10].description,
    layout: [
      '############',
      '# T      T #',
      '#  ######  #',
      '# B#    #  #',
      '#       #B #',
      '#  #### B  #',
      '#        T #',
      '############',
    ],
    initialPlayerPosition: BoardPosition(row: 5, column: 9),
  ),
  SokobanLevel(
    number: 12,
    title: levelCopy[11].title,
    description: levelCopy[11].description,
    layout: [
      '###########',
      '# B  T    #',
      '# ### ### #',
      '# # BT  # #',
      '# # ### # #',
      '# B     T #',
      '###########',
    ],
    initialPlayerPosition: BoardPosition(row: 1, column: 1),
  ),
  SokobanLevel(
    number: 13,
    title: levelCopy[12].title,
    description: levelCopy[12].description,
    layout: [
      '############',
      '#  T B BT  #',
      '# ## ## ## #',
      '#          #',
      '# ##    ## #',
      '# T B      #',
      '############',
    ],
    initialPlayerPosition: BoardPosition(row: 1, column: 6),
  ),
  SokobanLevel(
    number: 14,
    title: levelCopy[13].title,
    description: levelCopy[13].description,
    layout: [
      '#############',
      '# T     B T #',
      '# B### ###  #',
      '#     #     #',
      '# ###   ### #',
      '#     #     #',
      '# B### ###  #',
      '# T   B   T #',
      '#############',
    ],
    initialPlayerPosition: BoardPosition(row: 1, column: 7),
  ),
];
