import '../models/board_position.dart';
import '../models/sokoban_level.dart';
import 'level_copy.dart';

final List<SokobanLevel> introductoryLevels = [
  SokobanLevel(
    number: 1,
    title: levelCopy[0].title,
    description: levelCopy[0].description,
    layout: [
      '_______________',
      '_______________',
      '_____###_______',
      '_____#T#_______',
      '____##B####____',
      '____#TB BT#____',
      '____###B###____',
      '______#T#______',
      '______###______',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 5, column: 7),
  ),
  SokobanLevel(
    number: 2,
    title: levelCopy[1].title,
    description: levelCopy[1].description,
    layout: [
      '_______________',
      '_____#####_____',
      '_____#   #_____',
      '___###B#T##____',
      '___#   B  #____',
      '___#    T##____',
      '___#   B  #____',
      '___###T####____',
      '_____###_______',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 4),
  ),

  SokobanLevel(
    number: 3,
    title: levelCopy[2].title,
    description: levelCopy[2].description,
    layout: [
      '_______________',
      '____### ###____',
      '____#T #  #____',
      '____#  B  #____',
      '____#T    #____',
      '____#   B #____',
      '____#     #____',
      '____#######____',
      '_______________',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 7),
  ),
  SokobanLevel(
    number: 4,
    title: levelCopy[3].title,
    description: levelCopy[3].description,
     layout: [
      '  #####        ',
      '  #   # ###    ',
      '  # BB# #T#    ',
      '  # B # #T#    ',
      '  ### ###T#    ',
      '    #     #    ',
      '   ##  #  #    ',
      '   #   #  #    ',
      '   #   ####    ',
      '   #####       ',
    ],
    initialPlayerPosition: BoardPosition(row: 1, column: 3),
  ),
  SokobanLevel(
    number: 5,
    title: levelCopy[4].title,
    description: levelCopy[4].description,
    layout: [
      '  #######      ',
      '  #     ###    ',
      ' ##B###   #    ',
      ' #   B  B #    ',
      ' # TT# B ##    ',
      ' ##TT#   #     ',
      '  ########     ',
      '               ',
      '               ',
      '               ',
    ],
    initialPlayerPosition: BoardPosition(row: 3, column: 3),
  ),
  SokobanLevel(
    number: 6,
    title: levelCopy[5].title,
    description: levelCopy[5].description,
    layout: [
      '     #####     ',
      '  ####   #     ',
      '  #  #B  ####  ',
      '  # BB      #  ',
      '  #   #B B# #  ',
      '  ### #   # #  ',
      '   #  ##### #  ',
      '   #  TTTTT #  ',
      '   ##########  ',
      '               ',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 3),
  ),
  SokobanLevel(
    number: 7,
    title: levelCopy[2].title,
    description: levelCopy[2].description,
    layout: [
      '_______________',
      '____### ###____',
      '____#T #  #____',
      '____#  B  #____',
      '____#T    #____',
      '____#   B #____',
      '____#     #____',
      '____#######____',
      '_______________',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 7),
  ),
  SokobanLevel(
    number: 8,
    title: levelCopy[2].title,
    description: levelCopy[2].description,
    layout: [
      '_______________',
      '____### ###____',
      '____#T #  #____',
      '____#  B  #____',
      '____#T    #____',
      '____#   B #____',
      '____#     #____',
      '____#######____',
      '_______________',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 7),
  ),
  SokobanLevel(
    number: 9,
    title: levelCopy[2].title,
    description: levelCopy[2].description,
    layout: [
      '_______________',
      '____### ###____',
      '____#T #  #____',
      '____#  B  #____',
      '____#T    #____',
      '____#   B #____',
      '____#     #____',
      '____#######____',
      '_______________',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 7),
  ),
  SokobanLevel(
    number: 10,
    title: levelCopy[2].title,
    description: levelCopy[2].description,
    layout: [
      '_______________',
      '____### ###____',
      '____#T #  #____',
      '____#  B  #____',
      '____#T    #____',
      '____#   B #____',
      '____#     #____',
      '____#######____',
      '_______________',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 7),
  ),
  SokobanLevel(
    number: 11,
    title: levelCopy[2].title,
    description: levelCopy[2].description,
    layout: [
      '_______________',
      '____### ###____',
      '____#T #  #____',
      '____#  B  #____',
      '____#T    #____',
      '____#   B #____',
      '____#     #____',
      '____#######____',
      '_______________',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 7),
  ),
  SokobanLevel(
    number: 12,
    title: levelCopy[2].title,
    description: levelCopy[2].description,
    layout: [
      '_______________',
      '____### ###____',
      '____#T #  #____',
      '____#  B  #____',
      '____#T    #____',
      '____#   B #____',
      '____#     #____',
      '____#######____',
      '_______________',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 7),
  ),
  SokobanLevel(
    number: 13,
    title: levelCopy[2].title,
    description: levelCopy[2].description,
    layout: [
      '_______________',
      '____### ###____',
      '____#T #  #____',
      '____#  B  #____',
      '____#T    #____',
      '____#   B #____',
      '____#     #____',
      '____#######____',
      '_______________',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 7),
  ),
  SokobanLevel(
    number: 14,
    title: levelCopy[2].title,
    description: levelCopy[2].description,
    layout: [
      '_______________',
      '____### ###____',
      '____#T #  #____',
      '____#  B  #____',
      '____#T    #____',
      '____#   B #____',
      '____#     #____',
      '____#######____',
      '_______________',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 7),
  ),
  SokobanLevel(
    number: 15,
    title: levelCopy[2].title,
    description: levelCopy[2].description,
    layout: [
      '_______________',
      '____### ###____',
      '____#T #  #____',
      '____#  B  #____',
      '____#T    #____',
      '____#   B #____',
      '____#     #____',
      '____#######____',
      '_______________',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 7),
  ),
  SokobanLevel(
    number: 16,
    title: levelCopy[2].title,
    description: levelCopy[2].description,
    layout: [
      '_______________',
      '____### ###____',
      '____#T #  #____',
      '____#  B  #____',
      '____#T    #____',
      '____#   B #____',
      '____#     #____',
      '____#######____',
      '_______________',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 7),
  ),
  SokobanLevel(
    number: 17,
    title: levelCopy[2].title,
    description: levelCopy[2].description,
    layout: [
      '_______________',
      '____### ###____',
      '____#T #  #____',
      '____#  B  #____',
      '____#T    #____',
      '____#   B #____',
      '____#     #____',
      '____#######____',
      '_______________',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 7),
  ),
  SokobanLevel(
    number: 18,
    title: levelCopy[2].title,
    description: levelCopy[2].description,
    layout: [
      '_______________',
      '____### ###____',
      '____#T #  #____',
      '____#  B  #____',
      '____#T    #____',
      '____#   B #____',
      '____#     #____',
      '____#######____',
      '_______________',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 7),
  ),
  SokobanLevel(
    number: 19,
    title: levelCopy[2].title,
    description: levelCopy[2].description,
    layout: [
      '_______________',
      '____### ###____',
      '____#T #  #____',
      '____#  B  #____',
      '____#T    #____',
      '____#   B #____',
      '____#     #____',
      '____#######____',
      '_______________',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 7),
  ),
  SokobanLevel(
    number: 20,
    title: levelCopy[2].title,
    description: levelCopy[2].description,
    layout: [
      '_______________',
      '____### ###____',
      '____#T #  #____',
      '____#  B  #____',
      '____#T    #____',
      '____#   B #____',
      '____#     #____',
      '____#######____',
      '_______________',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 7),
  ),
 SokobanLevel(
    number: 21,
    title: levelCopy[0].title,
    description: levelCopy[0].description,
    layout: [
      '_______________',
      '_______________',
      '_____###_______',
      '_____#T#_______',
      '____##B####____',
      '____#TB BT#____',
      '____###B###____',
      '______#T#______',
      '______###______',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 5, column: 7),
  ),

  SokobanLevel(
    number: 22,
    title: levelCopy[1].title,
    description: levelCopy[1].description,
    layout: [
      '_______________',
      '_____#####_____',
      '_____#   #_____',
      '___###B#T##____',
      '___#   B  #____',
      '___#    T##____',
      '___#   B  #____',
      '___###T####____',
      '_____###_______',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 4),
  ),

  SokobanLevel(
    number: 23,
    title: levelCopy[2].title,
    description: levelCopy[2].description,
    layout: [
      '_______________',
      '____### ###____',
      '____#T #  #____',
      '____#  B  #____',
      '____#T    #____',
      '____#   B #____',
      '____#     #____',
      '____#######____',
      '_______________',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 7),
  ),
  SokobanLevel(
    number: 24,
    title: levelCopy[2].title,
    description: levelCopy[2].description,
    layout: [
      '_______________',
      '____### ###____',
      '____#T #  #____',
      '____#  B  #____',
      '____#T    #____',
      '____#   B #____',
      '____#     #____',
      '____#######____',
      '_______________',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 7),
  ),
  SokobanLevel(
    number: 25,
    title: levelCopy[2].title,
    description: levelCopy[2].description,
    layout: [
      '_______________',
      '____### ###____',
      '____#T #  #____',
      '____#  B  #____',
      '____#T    #____',
      '____#   B #____',
      '____#     #____',
      '____#######____',
      '_______________',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 7),
  ),
  SokobanLevel(
    number: 26,
    title: levelCopy[2].title,
    description: levelCopy[2].description,
    layout: [
      '_______________',
      '____### ###____',
      '____#T #  #____',
      '____#  B  #____',
      '____#T    #____',
      '____#   B #____',
      '____#     #____',
      '____#######____',
      '_______________',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 7),
  ),
  SokobanLevel(
    number: 27,
    title: levelCopy[2].title,
    description: levelCopy[2].description,
    layout: [
      '_______________',
      '____### ###____',
      '____#T #  #____',
      '____#  B  #____',
      '____#T    #____',
      '____#   B #____',
      '____#     #____',
      '____#######____',
      '_______________',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 7),
  ),
  SokobanLevel(
    number: 28,
    title: levelCopy[2].title,
    description: levelCopy[2].description,
    layout: [
      '_______________',
      '____### ###____',
      '____#T #  #____',
      '____#  B  #____',
      '____#T    #____',
      '____#   B #____',
      '____#     #____',
      '____#######____',
      '_______________',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 7),
  ),
  SokobanLevel(
    number: 29,
    title: levelCopy[2].title,
    description: levelCopy[2].description,
    layout: [
      '_______________',
      '____### ###____',
      '____#T #  #____',
      '____#  B  #____',
      '____#T    #____',
      '____#   B #____',
      '____#     #____',
      '____#######____',
      '_______________',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 7),
  ),
  SokobanLevel(
    number: 30,
    title: levelCopy[2].title,
    description: levelCopy[2].description,
    layout: [
      '_______________',
      '____### ###____',
      '____#T #  #____',
      '____#  B  #____',
      '____#T    #____',
      '____#   B #____',
      '____#     #____',
      '____#######____',
      '_______________',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 7),
  ),
  SokobanLevel(
    number: 31,
    title: levelCopy[2].title,
    description: levelCopy[2].description,
    layout: [
      '_______________',
      '____### ###____',
      '____#T #  #____',
      '____#  B  #____',
      '____#T    #____',
      '____#   B #____',
      '____#     #____',
      '____#######____',
      '_______________',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 7),
  ),
  SokobanLevel(
    number: 32,
    title: levelCopy[2].title,
    description: levelCopy[2].description,
    layout: [
      '_______________',
      '____### ###____',
      '____#T #  #____',
      '____#  B  #____',
      '____#T    #____',
      '____#   B #____',
      '____#     #____',
      '____#######____',
      '_______________',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 7),
  ),
  SokobanLevel(
    number: 33,
    title: levelCopy[2].title,
    description: levelCopy[2].description,
    layout: [
      '_______________',
      '____### ###____',
      '____#T #  #____',
      '____#  B  #____',
      '____#T    #____',
      '____#   B #____',
      '____#     #____',
      '____#######____',
      '_______________',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 7),
  ),
  SokobanLevel(
    number: 34,
    title: levelCopy[2].title,
    description: levelCopy[2].description,
    layout: [
      '_______________',
      '____### ###____',
      '____#T #  #____',
      '____#  B  #____',
      '____#T    #____',
      '____#   B #____',
      '____#     #____',
      '____#######____',
      '_______________',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 7),
  ),
  SokobanLevel(
    number: 35,
    title: levelCopy[2].title,
    description: levelCopy[2].description,
    layout: [
      '_______________',
      '____### ###____',
      '____#T #  #____',
      '____#  B  #____',
      '____#T    #____',
      '____#   B #____',
      '____#     #____',
      '____#######____',
      '_______________',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 7),
  ),
  SokobanLevel(
    number: 36,
    title: levelCopy[2].title,
    description: levelCopy[2].description,
    layout: [
      '_______________',
      '____### ###____',
      '____#T #  #____',
      '____#  B  #____',
      '____#T    #____',
      '____#   B #____',
      '____#     #____',
      '____#######____',
      '_______________',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 7),
  ),
  SokobanLevel(
    number: 37,
    title: levelCopy[2].title,
    description: levelCopy[2].description,
    layout: [
      '_______________',
      '____### ###____',
      '____#T #  #____',
      '____#  B  #____',
      '____#T    #____',
      '____#   B #____',
      '____#     #____',
      '____#######____',
      '_______________',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 7),
  ),
  SokobanLevel(
    number: 38,
    title: levelCopy[2].title,
    description: levelCopy[2].description,
    layout: [
      '_______________',
      '____### ###____',
      '____#T #  #____',
      '____#  B  #____',
      '____#T    #____',
      '____#   B #____',
      '____#     #____',
      '____#######____',
      '_______________',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 7),
  ),
  SokobanLevel(
    number: 39,
    title: levelCopy[2].title,
    description: levelCopy[2].description,
    layout: [
      '_______________',
      '____### ###____',
      '____#T #  #____',
      '____#  B  #____',
      '____#T    #____',
      '____#   B #____',
      '____#     #____',
      '____#######____',
      '_______________',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 7),
  ),
  SokobanLevel(
    number: 40,
    title: levelCopy[2].title,
    description: levelCopy[2].description,
    layout: [
      '_______________',
      '____### ###____',
      '____#T #  #____',
      '____#  B  #____',
      '____#T    #____',
      '____#   B #____',
      '____#     #____',
      '____#######____',
      '_______________',
      '_______________',
    ],
    initialPlayerPosition: BoardPosition(row: 4, column: 7),
  ),
];
